#!/usr/bin/env zsh

# uncomment this for profiling zshrc
# zmodload zsh/zprof

# -------------------------------- Oh My ZSH config --------------------------------
ZSH_THEME="agnoster"
zstyle ':omz:update' mode reminder
zstyle ':omz:update' frequency 30
plugins=(
  git
  virtualenv
  fzf-tab
  zsh-autosuggestions
  zsh-syntax-highlighting
)
fpath+=${ZSH_CUSTOM:-${ZSH:-~/.oh-my-zsh}/custom}/plugins/zsh-completions/src
source $HOME/.oh-my-zsh/oh-my-zsh.sh

# -------------------------------- User + Locale config --------------------------------
DEFAULT_USER="apathak"
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# -------------------------------- Path config --------------------------------
export MANPATH="/usr/local/man:$MANPATH"
export PATH="$HOME/.local/bin:$PATH"
export XDG_CONFIG_HOME=$HOME/.config    # https://wiki.archlinux.org/index.php/XDG_Base_Directory_support
export PERSONAL=$HOME/code/personal
export DOTFILES=$PERSONAL/dotfiles
export WORKSPACE=$PERSONAL/workspace

# -------------------------------- env config --------------------------------
# source os-specific-env
source $HOME/.env-system.sh

# source all app-specific envs
typeset config_files
config_files=($DOTFILES/apps/**/env.sh)
for file in "${config_files[@]}"
do
  source $file
done
unset config_files

# -------------------------------- Completions config --------------------------------
skip_global_compinit=1
autoload -Uz compinit bashcompinit
compinit
bashcompinit
setopt correct
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=248" # fish like autosuggestions
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'

# -------------------------------- History config --------------------------------
[ -z "$HISTFILE" ] && HISTFILE="$WORKSPACE/zsh_history"
HISTSIZE=10000
SAVEHIST=$HISTSIZE
HISTDUP=erase
setopt extended_history       # record timestamp of command in HISTFILE
setopt hist_expire_dups_first # delete duplicates first when HISTFILE size exceeds HISTSIZE
setopt hist_ignore_all_dups   # purge older duplicates (in memory)
setopt hist_save_no_dups      # do not write duplicates to HISTFILE
setopt hist_ignore_space      # ignore commands that start with space
setopt hist_verify            # show command with history expansion to user before running it
setopt inc_append_history     # add commands to HISTFILE incrementally instead of waiting till shell exits
setopt share_history          # share command history data

# -------------------------------- misc config --------------------------------
unsetopt BEEP # turn off terminal beep

# -------------------------------- completion styling --------------------------------
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}' # case insensitive completions
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}" # colored completions
zstyle ':completion:*' menu no
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'ls --color $realpath'
zstyle ':fzf-tab:complete:__zoxide_z:*' fzf-preview 'ls --color $realpath'

# -------------------------------- keybindings --------------------------------
bindkey '^p' history-search-backward
bindkey '^n' history-search-forward

# -------------------------------- shell integrations --------------------------------
eval "$(fzf --zsh)"
eval "$(zoxide init --cmd cd zsh)"

# uncomment this for profiling zshrc
# zprof
