#!/usr/bin/env zsh

# uncomment this for profiling zshrc
# zmodload zsh/zprof

# set up locales
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# turn off terminal beep
unsetopt BEEP

# set up global directories
export XDG_CONFIG_HOME=$HOME/.config    # https://wiki.archlinux.org/index.php/XDG_Base_Directory_support
export PERSONAL=$HOME/code/personal
export DOTFILES=$PERSONAL/dotfiles
export WORKSPACE=$PERSONAL/workspace

# source system-specific-env
source $HOME/.env-system.sh

# source all app-specific env.sh files
typeset config_files
config_files=($DOTFILES/apps/**/env.sh)
for file in "${config_files[@]}"
do
  source $file
done
unset config_files

# zsh completions configuration
skip_global_compinit=1
autoload -Uz compinit bashcompinit
compinit
bashcompinit
setopt correct
# fish like autosuggestions
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=248"

# zsh history configuration
# ref: https://github.com/robbyrussell/oh-my-zsh/blob/master/lib/history.zsh
[ -z "$HISTFILE" ] && HISTFILE="$WORKSPACE/zsh_history"
HISTSIZE=50000
SAVEHIST=10000
setopt extended_history       # record timestamp of command in HISTFILE
setopt hist_expire_dups_first # delete duplicates first when HISTFILE size exceeds HISTSIZE
setopt hist_ignore_dups       # ignore duplicated commands history list
setopt hist_ignore_space      # ignore commands that start with space
setopt hist_verify            # show command with history expansion to user before running it
setopt inc_append_history     # add commands to HISTFILE in order of execution
setopt share_history          # share command history data


# prompt configuration
# initialize the prompt system
autoload -Uz promptinit; promptinit

# Option 1: Powerlevel9k prompt
# POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context virtualenv dir vcs)
# POWERLEVEL9K_DISABLE_RPROMPT=true
# DEFAULT_USER=$USER
# POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
# POWERLEVEL9K_SHORTEN_DELIMITER=""
# POWERLEVEL9K_SHORTEN_STRATEGY="truncate_from_right"
# POWERLEVEL9K_DIR_HOME_BACKGROUND=024
# POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND=250
# POWERLEVEL9K_DIR_ETC_BACKGROUND=024
# POWERLEVEL9K_DIR_DEFAULT_BACKGROUND=024
# POWERLEVEL9K_VIRTUALENV_BACKGROUND='039'
# POWERLEVEL9K_VCS_CLEAN_FOREGROUND='black'
# POWERLEVEL9K_VCS_CLEAN_BACKGROUND='112'
# POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='black'
# POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='178'
# POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='black'
# POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='178'

# Option 2: Starship prompt, https://github.com/starship/starship
# eval "$(starship init zsh)"

# uncomment this for profiling zshrc
# zprof