#!/bin/bash

export PATH=$PATH:$HOME/Library/Python/2.7/bin

# powerline
export POWERLINE_LIB=$HOME/Library/Python/2.7/lib/python/site-packages/powerline

# brew
# Ensure coreutils and brew-installed binaries take precedence
PATH="/usr/local/opt/coreutils/libexec/gnubin:/usr/local/bin:/usr/local/sbin:$PATH"
MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"
alias brewup='brew update; brew upgrade; brew cleanup; brew doctor'