#!/bin/bash
BREW_PYTHON_HOME=/usr/local/Cellar/python@2/2.7.15_2/Frameworks/Python.framework/Versions/2.7
export PATH=$PATH:$BREW_PYTHON_HOME/bin

# powerline
export POWERLINE_LIB=$BREW_PYTHON_HOME/lib/python2.7/site-packages/powerline

# brew
# Ensure coreutils and brew-installed binaries take precedence
PATH="/usr/local/opt/coreutils/libexec/gnubin:/usr/local/bin:/usr/local/sbin:$PATH"
MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"
alias brewup='brew update; brew upgrade; brew cleanup; brew doctor'