# taps
tap 'homebrew/cask-fonts'


# CLI

brew 'mas'
brew 'zsh'
brew 'vim'
brew 'git'
brew 'go'
brew 'tree'
brew 'autojump'
brew 'coreutils'
brew 'binutils'
brew 'diffutils'
brew 'findutils'
brew 'gawk'
brew 'gnu-sed'
brew 'gnu-tar'
brew 'gnu-which'
brew 'gnutls'
brew 'grep'
brew 'gzip'
brew 'screen'
brew 'watch'
brew 'gnupg'
brew 'gnupg2'
brew 'make'
brew 'cmake'
brew 'gcc'
brew 'less'
brew 'rsync'
brew 'unzip'
brew 'ripgrep'
brew 'fd'
brew 'shellcheck'


# GUI

cask_args appdir: "/Applications"
cask 'iterm2'
cask 'google-chrome'
cask 'rectangle'
cask 'vlc'
cask 'dropbox'
cask 'skype'
cask 'slack'
cask 'google-backup-and-sync'
cask 'pycharm'
cask 'evernote'
# cask 'alfred' - installs alfred4
cask 'appcleaner'
cask 'visual-studio-code'
cask 'tunnelbear'
cask 'kitty'
cask 'monitorcontrol'
mas 'tomato one', id: 907364780
mas 'reeder 3', id: 880001334
mas 'AutoMute', id: 1118136179

# extras

# fonts
cask 'font-meslo-nerd-font-mono'
cask 'font-hack-nerd-font'



