brew 'mas'
brew 'bash', link: true, args: ['overwrite']
brew 'zsh', link: true, args: ['overwrite']
brew 'vim', args: ['override-system-vi']
brew 'git', link: true, args: ['overwrite']
brew 'git-lfs'
brew 'node'
brew 'go'
brew 'python3'
brew 'tree'
brew 'autojump'

brew 'coreutils'
tap 'homebrew/dupes'
tap 'caskroom/versions'
brew 'binutils'
brew 'diffutils'
brew 'findutils'
brew 'gawk'
brew 'gnu-sed', args: ['with-default-names']
brew 'gnu-tar', args: ['with-default-names']
brew 'gnu-which', args: ['with-default-names']
brew 'gnutls'
brew 'grep', args: ['with-default-names']
brew 'gzip'
brew 'screen'
brew 'watch'
brew 'gnupg'
brew 'gnupg2'
brew 'make'
brew 'cmake'
brew 'gcc'
brew 'less'
brew 'rsync'
brew 'unzip'
brew 'maven'

cask_args appdir: "/Applications"
tap 'caskroom/cask'
cask 'iterm2'
cask 'google-chrome'
cask 'spectacle'
cask 'vlc'
cask 'dropbox'
cask 'skype'
cask 'slack'
cask 'google-backup-and-sync'
cask 'pycharm'
cask 'webstorm'
cask 'intellij-idea'
cask 'evernote'
cask 'alfred'
cask 'appcleaner'
cask 'visual-studio-code'
cask 'dash'
cask 'calibre'
cask 'tunnelbear'

tap 'caskroom/fonts'
cask 'font-meslo-nerd-font-mono'

mas 'tomato one', id: 907364780
mas 'reeder 3', id: 880001334
mas 'AutoMute', id: 1118136179



