# set up locales
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# set up global directories
export XDG_CONFIG_HOME=~/.config    # https://wiki.archlinux.org/index.php/XDG_Base_Directory_support
export CODE=~/code
export DOTFILES=$CODE/personal/dotfiles

# Load .bashrc if it exists
test -f ~/.bashrc && source ~/.bashrc

# preferred aliases
alias ll="ls -lh"

# Load all .bash files located in dotfiles
typeset config_files
config_files=($DOTFILES/**/*.bash)
for file in "${config_files[@]}"
do
  source $file
done
unset config_files

# store your ssh passphrase in the keychain.
# /usr/bin/ssh-add -K ~/.ssh/id_rsa

# set up color in terminal
GRCFILE=/usr/local/etc/grc.bashrc
[[ -s $GRCFILE ]] && source $GRCFILE

# powerline shell prompt # https://github.com/banga/powerline-shell
function _update_ps1() {
    PS1="$(powerline-shell $?)"
}
if [ "$TERM" != "linux" ]; then
    PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
fi

# better bash history
HISTSIZE=10000
HISTFILESIZE=20000
shopt -s histappend
# important: execute this command *after* the prompt has been designed
export PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"

# set up Java-related env
export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/"

#Skymind-related configurations
export CLOUD_CREDS_DIR="/Users/abhishek/Documents/cloudCreds/"
export SKIL_HOME="/Users/abhishek/opt/skil"
export SKIL_LOG_DIR=$SKIL_HOME/logs
export SKIL_PID_FILE=$SKIL_HOME/skil.pid
export SKIL_LICENSE_PATH=/Users/abhishek/code/skymind/skil-server/skilaspects/src/test/resources/skil-trial-license.txt
export SKIL_PUBLIC_KEY_PATH=/Users/abhishek/code/skymind/skil-server/skil-test-resources/src/main/resources/skil-trial-public.txt
export SKIL_CLASS_PATH=$SKIL_HOME/lib/*:$SKIL_HOME/native/*:$SKIL_HOME/lib/ext/*:$SKIL_HOME/jackson-2.5.1/*
#export FORCE_UPDATE_TO_DB=true
export SKIL_DEBUG_MODE=false
# alias to  update a skil subpackage in SKIL_HOME
alias skilup="mvn clean package -DskipTests && cp $PWD/target/*.jar $SKIL_HOME/lib && $SKIL_HOME/sbin/stop-skil-daemon && sleep 10 && $SKIL_HOME/sbin/start-skil-daemon"